name: ${name}
version: ${version}
main: org.crashvibe.FGateBukkit.FGateBukkit
description: ${description}
api-version: '1.13'
folia-supported: true

softdepend:
  - PlaceholderAPI
authors:
  - CrashVibe
